import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { getAuthenticatedAppForUser } from "@/lib/firebase/serverApp";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   favicon: "/favicon.ico",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const doc = await getAuthenticatedAppForUser();

  return (
    <html lang="en">
      <body>
        <Providers currentUser={doc.currentUser}>{children}</Providers>
      </body>
    </html>
  );
}
